def LoginToDeepSeek(evar, pvar, page, url="https://chat.deepseek.com"):
    page.goto(url)
    page.get_by_placeholder("Phone number / email address").fill(evar)
    page.get_by_placeholder("Password").fill(pvar)
    page.keyboard.press("Tab")
    page.keyboard.press("Tab")
    page.keyboard.press("Tab")
    page.keyboard.press("Tab")
    page.keyboard.press("Enter")
    # page.get_by_role("button").nth(0).click()